// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u8().primaryKey(),
  y: __t.f64(),
  velocity: __t.f64(),
  currentFloor: __t.u8().name("current_floor"),
  targetFloor: __t.u8().name("target_floor"),
  phase: __t.string(),
  door: __t.f64(),
  queue: __t.byteArray(),
  phaseTime: __t.f64().name("phase_time"),
  landingDoors: __t.array(__t.bool()).name("landing_doors"),
  landingOpen: __t.array(__t.f64()).name("landing_open"),
  sampleMicros: __t.i64().name("sample_micros"),
});
