// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  slot: __t.u8(),
  online: __t.bool(),
  connectionId: __t.option(__t.connectionId()).name("connection_id"),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  vx: __t.f64(),
  vy: __t.f64(),
  vz: __t.f64(),
  yaw: __t.f64(),
  grounded: __t.bool(),
  crouch: __t.bool(),
  inCab: __t.bool().name("in_cab"),
  onRoof: __t.bool().name("on_roof"),
  jumpActive: __t.bool().name("jump_active"),
  jumpSeq: __t.u32().name("jump_seq"),
  seq: __t.u32(),
  sampleMicros: __t.i64().name("sample_micros"),
  inputForward: __t.f64().name("input_forward"),
  inputRight: __t.f64().name("input_right"),
  inputYaw: __t.f64().name("input_yaw"),
  inputSprint: __t.bool().name("input_sprint"),
  inputCrouch: __t.bool().name("input_crouch"),
  inputJumpHeld: __t.bool().name("input_jump_held"),
  inputJumpSeq: __t.u32().name("input_jump_seq"),
  inputSeq: __t.u32().name("input_seq"),
  inputMicros: __t.i64().name("input_micros"),
});
