// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  forward: __t.f64(),
  right: __t.f64(),
  yaw: __t.f64(),
  sprint: __t.bool(),
  crouch: __t.bool(),
  jumpHeld: __t.bool(),
  jumpSeq: __t.u32(),
  seq: __t.u32(),
};
