// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Elevator = __t.object("Elevator", {
  id: __t.u8(),
  y: __t.f64(),
  velocity: __t.f64(),
  currentFloor: __t.u8(),
  targetFloor: __t.u8(),
  phase: __t.string(),
  door: __t.f64(),
  queue: __t.byteArray(),
  phaseTime: __t.f64(),
  landingDoors: __t.array(__t.bool()),
  landingOpen: __t.array(__t.f64()),
  sampleMicros: __t.i64(),
});
export type Elevator = __Infer<typeof Elevator>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  slot: __t.u8(),
  online: __t.bool(),
  connectionId: __t.option(__t.connectionId()),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  vx: __t.f64(),
  vy: __t.f64(),
  vz: __t.f64(),
  yaw: __t.f64(),
  grounded: __t.bool(),
  crouch: __t.bool(),
  inCab: __t.bool(),
  onRoof: __t.bool(),
  jumpActive: __t.bool(),
  jumpSeq: __t.u32(),
  seq: __t.u32(),
  sampleMicros: __t.i64(),
  inputForward: __t.f64(),
  inputRight: __t.f64(),
  inputYaw: __t.f64(),
  inputSprint: __t.bool(),
  inputCrouch: __t.bool(),
  inputJumpHeld: __t.bool(),
  inputJumpSeq: __t.u32(),
  inputSeq: __t.u32(),
  inputMicros: __t.i64(),
});
export type Player = __Infer<typeof Player>;

export const Tick = __t.object("Tick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type Tick = __Infer<typeof Tick>;

