// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import HailFloorReducer from "../hail_floor_reducer";
import JoinReducer from "../join_reducer";
import RespawnReducer from "../respawn_reducer";
import SelectFloorReducer from "../select_floor_reducer";
import SetDoorOpenReducer from "../set_door_open_reducer";
import SubmitInputReducer from "../submit_input_reducer";
import ToggleLandingDoorReducer from "../toggle_landing_door_reducer";

export type HailFloorParams = __Infer<typeof HailFloorReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type RespawnParams = __Infer<typeof RespawnReducer>;
export type SelectFloorParams = __Infer<typeof SelectFloorReducer>;
export type SetDoorOpenParams = __Infer<typeof SetDoorOpenReducer>;
export type SubmitInputParams = __Infer<typeof SubmitInputReducer>;
export type ToggleLandingDoorParams = __Infer<typeof ToggleLandingDoorReducer>;

